# Generated by Django 6.0.1 on 2026-02-12 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=50000)),
                ('featured_img', models.ImageField(upload_to='news/featured_imgs/%d/%m/%y')),
                ('tags', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')])),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
