# Generated by Django 6.0.1 on 2026-02-12 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 14, 49, 39, 284354, tzinfo=datetime.timezone.utc)),
        ),
    ]
