# Generated by Django 6.0.1 on 2026-02-12 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_published_at_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
    ]
