# Generated by Django 6.0.1 on 2026-01-26 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='banner_videos')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
