# Generated by Django 6.0.1 on 2026-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academicqualification_country_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
