# Generated by Django 6.0.1 on 2026-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_country_slug_alter_nationality_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='didyouknow',
            name='featured_img',
            field=models.ImageField(blank=True, default='facts/default_img/default.jpg', upload_to='facts/featured_images'),
        ),
    ]
