# Generated by Django 6.0.1 on 2026-01-28 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_academicqualification_country_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=200)),
                ('biography', models.TextField(max_length=10000)),
                ('religion', models.CharField(blank=True, default='', max_length=200)),
                ('academic_history', models.TextField(max_length=5000)),
                ('home_town', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
                ('academic_qualifications', models.ManyToManyField(blank=True, to='core.academicqualification')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.nationality')),
            ],
        ),
    ]
