# Generated by Django 6.0.1 on 2026-01-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0002_celebritynews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celebritynews',
            old_name='mews_text',
            new_name='news_text',
        ),
    ]
