# Generated by Django 6.0.1 on 2026-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_rename_mews_text_celebritynews_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='picture',
            field=models.ImageField(default='celebrities/pictures/default/default-pic.jpg', upload_to='celebrities/pictures/'),
        ),
    ]
