# Generated by Django 6.0.1 on 2026-01-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='banner_img',
            field=models.ImageField(null=True, upload_to='series/episodes/banner_images'),
        ),
        migrations.AddField(
            model_name='episode',
            name='director',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='episode',
            name='production_countries',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='trailer',
            field=models.FileField(null=True, upload_to='series/episodes/trailers'),
        ),
        migrations.AddField(
            model_name='series',
            name='banner_img',
            field=models.ImageField(null=True, upload_to='series/banner_images'),
        ),
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='series',
            name='num_of_episode',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='series',
            name='production_countries',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='series',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='trailer',
            field=models.FileField(null=True, upload_to='series/trailers'),
        ),
    ]
