# Generated by Django 6.0.1 on 2026-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_episode_banner_img_episode_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
