# Generated by Django 6.0.1 on 2026-01-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_series_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
