# Generated by Django 6.0.1 on 2026-01-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_series_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='num_of_episode',
            new_name='num_of_episodes',
        ),
    ]
