# Generated by Django 6.0.1 on 2026-01-26 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=10000)),
                ('banner_img', models.ImageField(upload_to='movies/banner_images')),
                ('trailer', models.FileField(upload_to='movies/trailers')),
                ('production_year', models.IntegerField(max_length=5)),
                ('producer', models.CharField(blank=True, default=True, max_length=200)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('upload_time', models.TimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
