# Generated by Django 6.0.1 on 2026-01-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='production_year',
            field=models.IntegerField(),
        ),
    ]
