# Generated by Django 6.0.1 on 2026-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_production_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_year',
            field=models.PositiveIntegerField(),
        ),
    ]
